### ISSUE TITLE
Changing configuration not applying and freezing the execution

### ISSUE THREAD

**Issue by alu0100902341** [etsiiull/SIMDE#20]
To see the issue set configuration at:

UF Suma Entera: 3
UF Memoria: 3
UF Salto: 2
Emisión: 7

Use the program and the .mem at code.zip

[code.zip](https://github.com/etsiiull/SIMDE/files/2080171/code.zip)

**Comment by adrianabreu** [comment]
Thank you for reporting this, I'll try to check it with a few tests

**Comment by adrianabreu** [comment]
It should be fixed by now, thank you for reporting this :)
