### ISSUE TITLE
Review vulnerable dependencies

### ISSUE THREAD

**Issue by adrianabreu** [etsiiull/SIMDE#23]
Github is informing about vulnerable dependencies in the repo. Those dependencies should be updated in order to avoid this warning.

**Comment by adrianabreu** [comment]
One vulenerable dependency has been removed. The other one is related to bootstrap and simde should be fully merged with the VLIW implementation before changing to bootstrap 4.

**Comment by oxcabe** [comment]
Vulnerable dependencies updated in https://github.com/etsiiull/SIMDE/pull/50. Most of then were related to the `gitbook-cli` module. The command `npm audit` now returns: `found 0 vulnerabilities`.
