### ISSUE TITLE
Batch execution

### ISSUE THREAD

**Issue by icasrod** [etsiiull/SIMDE#6]
It would be advisable to add a "Batch execution" option in the "Options" menu. This option is useful for users interested only in the final result and number of execution cycles. This option is extremely useful for excercises where students have to look for the fastest configuration, or for the impact of a number of modifications in the machine performance.

**Comment by adrianabreu** [comment]
Seems a nice option to be implemented. How can we deal with the user interaction? 

My first choice would be to make something like this:
![image](https://user-images.githubusercontent.com/9080392/36993060-a99bf962-20a4-11e8-9a20-e22c565c67c4.png)

And at the end of the execution display a modal like this containing a table with the results within a table like this:
![image](https://user-images.githubusercontent.com/9080392/36993221-220ecf78-20a5-11e8-8169-af9a6b93fbdd.png)

Any suggestions about this?

**Comment by icasrod** [comment]
Instead of "Execution amount", use "Replications".
Instead of the result for every replication, a statistics summary (average, standard deviation, min, max) would be more than enough.
