### ISSUE TITLE
The Lexer is deprecated and some other parsing issues

### ISSUE THREAD

**Issue by endes0** [etsiiull/SIMDE#62]
The current package used as a lexer is [deprecated and was last update more than 8 years ago](https://www.npmjs.com/package/lex). Also, the lexer is only used in one (the code parser) of the 3 parsers that SIMDE has, and not even in its full potential. The other 2 parsers uses a mix of Regex expressions and string manipulations functions. As the current status of the parsers is not ideal*, I think a **great enhancement would be to refactor those using Regex expressions to their full potential**, avoiding using lexers or string manipulations functions.

*Some example of issues I found so far:

- A simple extra space can trick the memory content parser to skip a memory position
- The same with tabs on the VLIW parser
- While the VLIW parser does not need the instructions counter at all, it treats a mismatch as a fatal error
- In fact, an extra new line at the end of the file, which is automatically added on to the exported files from SIMDE Legacy, tricks the VLIW parser into thinking the instruction counter and the actual number of instructions mismatch. Adding a paint point from the user using SIMDE Legacy.

**Comment by oxcabe** [comment]
I agree. The current tools for parsing are heavily outdated and the overall implementation lacks organization and consistency.

Since we also discussed using parser combinators, I did a little research and found this library which could be helpful for having regex at scale for a parser and is maintained by Microsoft: https://www.npmjs.com/package/typescript-parsec

**Comment by oxcabe** [comment]
Or else it can be implemented locally, in a similar fashion like this + regex: https://dev.to/glebec/monadic-parser-combinators-an-interactive-js-tutorial-pt-1-3jbo

This is a close alternative (and the usage would be similar too) and allows us to avoid integrating more dependencies. In this case, parsec might also be way too powerful for the parsers we need in this project 🤷
