### ISSUE TITLE
Code redundancy with Opcodes

### ISSUE THREAD

**Issue by endes0** [etsiiull/SIMDE#71]
On the actual code, there is a recurrent source of bugs, those lies on how the core manages the Opcodes. Sometimes it uses [getFunctionalUnitType](https://github.com/etsiiull/SIMDE/blob/346e9a547b94454c8c17be04a7b75c3daa9cf363/src/core/Common/Code.ts#L160), that currently is incomplete(see https://github.com/etsiiull/SIMDE/commit/81972abea1035acf9cb282dcd7930a599833c63d), but other times there are just big opcodes switch statements spread across the code(like https://github.com/etsiiull/SIMDE/blob/346e9a547b94454c8c17be04a7b75c3daa9cf363/src/core/Superescalar/Superescalar.ts#L172 https://github.com/etsiiull/SIMDE/blob/346e9a547b94454c8c17be04a7b75c3daa9cf363/src/core/Superescalar/Superescalar.ts#L400 https://github.com/etsiiull/SIMDE/blob/346e9a547b94454c8c17be04a7b75c3daa9cf363/src/core/Superescalar/Superescalar.ts#L574 https://github.com/etsiiull/SIMDE/blob/346e9a547b94454c8c17be04a7b75c3daa9cf363/src/core/VLIW/VLIW.ts#L219 https://github.com/etsiiull/SIMDE/blob/346e9a547b94454c8c17be04a7b75c3daa9cf363/src/core/VLIW/VLIWOperation.ts#L88). 

So I think a good idea would be to try to move as many as possible opcodes switchs to the Opcodes file or similar. So, every time an Opcode or functional unit is modified or added, we don't potentially insert bugs.

**Comment by endes0** [comment]
Reopening this, as this was partially "fixed". Most of the logic with opcodes was moved to the Instruction.ts file, but as I said in the PR:

>  Instruction.ts is nowhere near as what we wanted to be like. We planned to convert it to an abstract class, with would have been inherited by a class for every kind of instruction (jump, load/store, etc ). Very Java inspired. But it ended being this horrible amalgam of switchs, ifs and opcodes comparisons.

Also there is still logic outside see: https://github.com/etsiiull/SIMDE/blob/d577cd8cfc7bb244ac8c1ba0ab42797ea3391797/src/core/Common/FunctionalUnit.ts#L158

**Comment by oxcabe** [comment]
Best course of action here is to have an Opcode.ts file with all definitions and functionality exclusive to opcodes.
